package like

import (
	"fmt"
	"testing"
)

func TestLike(t *testing.T) {
	r, _ := Like(
		//"TGGTTCAGTGCCACACATTGTAGATATTAAATATTTTATATTCAGTGACAGTCATAAACTTGTCCATTGTGTGTAAATAGTATTATGACTTTAACTCTGTGCACATTAGAATACAGTTCAGTTGGCGG",
		//[]byte("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGATAGGAAGAGCACACGTCTGAA"),
		[]byte("TTTCTTAGAGTGAAGAGTGTAAGGAATGCATTCAATTTTATCTTTTTAAATTTTTTTAAATTTATTTTTATTTTATTTTATTTATTTATTTTGAGACGGGGTCTTTCTTGTCACCca"),
		[]byte("GGCCATCTTGGCTCCTCCC"))
	fmt.Printf("%#v\n", r)
}
